version: '3'
services:
  app:
    container_name: 'python-dev'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    working_dir: '/var/www/html'
    volumes:
      - '.:/var/www/html'
    tty: true
